### ISSUE TITLE
U+16FE4 KHITAN SMALL SCRIPT FILLER is invisible

### ISSUE THREAD

**Issue by dscorbett** [notofonts/khitan-small-script#1]
### Fonts
NotoFangsongKSSRotated-Regular.otf
NotoFangsongKSSVertical-Regular.otf
NotoSerifKhitanSmallScript-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/khitan-small-script/releases/tag/NotoFangsongKSSRotated-v1.000
Site: https://github.com/notofonts/khitan-small-script/releases/tag/NotoFangsongKSSVertical-v1.000
Site: https://github.com/notofonts/khitan-small-script/releases/tag/NotoSerifKhitanSmallScript-v1.000
Date: 2023-01-16

### Font versions
Noto Fangsong KSS Rotated: Version 1.000;November 16, 2022;FontCreator 11.5.0.2427 64-bit
Noto Fangsong KSS Vertical: Version 1.000;November 16, 2022;FontCreator 11.5.0.2427 64-bit
Noto Serif Khitan Small Script: Version 1.000

### Issue
U+16FE4 KHITAN SMALL SCRIPT FILLER is always invisible. This can hide typos. It would be better if it had a dotted square glyph in unexpected contexts. It should only occur after the first character in a multi-character cluster.

### Character data
𘭔𖿤
U+18B54 KHITAN SMALL SCRIPT CHARACTER-18B54
U+16FE4 KHITAN SMALL SCRIPT FILLER

#### Noto Fangsong KSS Rotated
![𘭔𖿤](https://user-images.githubusercontent.com/1124347/212767750-a60d3fc8-4abd-44a2-8305-e02ac1b52e56.png)

#### Noto Fangsong KSS Vertical
![𘭔𖿤](https://user-images.githubusercontent.com/1124347/212767862-741edd40-89b4-4c02-8a28-3eb3c2f7a5de.png)

#### Noto Serif Khitan Small Script
![𘭔𖿤](https://user-images.githubusercontent.com/1124347/212767986-31394764-1fdc-40d0-9dc7-5c0dd34dee98.png)

#### Khitan Small Vertical
[Khitan Small Vertical](https://www.babelstone.co.uk/Fonts/KhitanSmall.html) is not a Noto font. The following is a more useful rendering of this misencoded or incomplete text:
![𘭔𖿤](https://user-images.githubusercontent.com/1124347/212768753-46a4590f-4e4f-4119-9d8b-b4dfe11cf4c0.png)

**Comment by simoncozens** [comment]
Well, that took me a while to find.

L2/18-213 says "the proposal author will submit a document providing guidance on what happens when the KHITAN SMALL SCRIPT FILLER appears in a position that is not between first and second graphic characters in a cluster." In 217, "It was agreed that the behavior of this format control should be completely documented in Unicode, including occurrence in unexpected contexts."

The next thing I found was L2/18-214, which argues that the glyph should say "KSSF", which SAD recommended in L2/18-300. I still can't find anything about what it should look like in unexpected contexts, but you're probably right.

**Comment by simoncozens** [comment]
Something may have changed, because Khitan Small Vertical now *also* hides the filler, in the same way as Noto Serif KSS does:

```
% shape ~/Downloads/KhitanSmallVertical.ttf -u 18b64,16fe4,18b64
[gid684=0@0,820+0|gid684=2+1024]
```

![shape](https://github.com/notofonts/khitan-small-script/assets/106728/62221d07-a5f8-43ce-b286-5f97a71bfd3b)

I have, however, made it visible when *not* in a cluster, so the behaviour is consistent with Khitan Small Vertical:

```
$ shape master_ttf/NotoSerifKhitanSmallScript-Regular.ttf -u 18B54,16fe4,18b54,18b54,20,16fe4
[u18B54.008=0+2000|kssf=0+0|u18B54.013=2+0|u18B54.015=3+0|space=4+600|u16FE4=4+1000]
```

![shape](https://github.com/notofonts/khitan-small-script/assets/106728/0eebc28e-c637-4105-be5a-bbd6f27ffdb4)
